/* Top-level interfaces to the Sail model.
   Ideally, this would be autogenerated.
 */

typedef int unit;
#define UNIT 0
typedef uint32_t mach_32bits;

void model_init(void);
void model_done(void);

unit zinit_platform(unit);
bool zstep(sail_int);
unit ztick_clock(unit);
unit ztick_platform(unit);

/* machine state */

extern mach_32bits zPC;

extern mach_32bits
        zr1,  zr2,  zr3,  zr4,  zr5,  zr6,  zr7,
  zr8,  zr9,  zr10, zr11, zr12, zr13, zr14, zr15,
  zr16, zr17, zr18, zr19, zr20, zr21, zr22, zr23,
  zr24, zr25, zr26, zr27, zr28, zr29, zr30, zr31;

extern mach_32bits
  zs0,  zs1,  zs2,  zs3,  zs4,  zs5,  zs6,  zs7,
  zs8,  zs9,  zs10, zs11, zs12, zs13, zs14, zs15,
  zs16, zs17, zs18, zs19, zs20, zs21, zs22, zs23,
  zs24, zs25, zs26, zs27, zs28, zs29, zs30, zs31;

extern mach_32bits zminstret;
